class ContextManager:
    def initialize_user(self, user_id): ...
    def get_changes(self, user_id, text): ...
    def update_context(self, user_id, frame, text): ...
    def update_from_voice(self, user_id, command): ...
